NotImplemented Error when using TF2.5
NotImplementedError: Cannot convert a symbolic Tensor (LSTM_1st_layer/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported